image: "ruby:2.3"

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq ruby-dev nodejs libsqlite3-dev graphviz
    - ruby -v
    - which ruby
    - gem install bundler --no-ri --no-rdoc
  script:
    - bundle install --jobs $(nproc) "${FLAGS[@]}"
    - bundle exec rails db:migrate
    - bundle exec rails db:seed
    - bundle exec rails test
  coverage: '/Coverage.*?\d+\s*\/\s*\d+\s*LOC\s*\((.*?%)\)\s*covered\./'

rubocop:
  stage: test
  script:
    - bundle install
    - bundle exec rubocop
  allow_failure: true

deploy_to_uat:
  stage: deploy
  image: "ubuntu:rolling"
  environment:
    name: uat
    url: https://uat.prodexity.com/bsimmcalc
  variables:
    DEPLOY_SERVER: uat.prodexity.com
    DEPLOY_USER: prodexityuat
    DEPLOY_APPNAME: bsimmcalc
    DEPLOY_ORIGIN: "ssh://git@gitlab.com/lengyelg/bsimmcalc"
  script:
    - touch ./key
    - chmod 600 ./key
    - echo $UAT_SSH_KEY | sed 's/ RSA PRIVATE KEY/RSAPRIVKEY/g' | sed 's/ /\n/g' | sed 's/RSAPRIVKEY/ RSA PRIVATE KEY/g' > ./key
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o SendEnv="CI_* DEPLOY_*" -i ./key $DEPLOY_USER@$DEPLOY_SERVER ./bin/deployrails.sh
    - rm ./key

deploy_to_prod:
  stage: deploy
  image: "ubuntu:rolling"
  environment:
    name: production
    url: https://bsimmcalc.prodexity.com
  script:
    - "echo 'deploying to prod...'"
  when: manual
  only:
    - master
