image: "ruby:2.3"

stages:
  - test
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq ruby-dev nodejs libsqlite3-dev graphviz
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc

test:
  stage: test
  script:
    - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
    - RAILS_ENV=test bundle exec rails db:migrate
    - RAILS_ENV=test bundle exec rails db:seed
    - RAILS_ENV=test bundle exec rails test
  coverage: '/Coverage.*?\d+\s*\/\s*\d+\s*LOC\s*\((.*?%)\)\s*covered\./'

rubocop:
  stage: test
  script:
    - bundle install
    - bundle exec rubocop
  allow_failure: true

deploy_to_uat:
  stage: deploy
  environment:
    name: uat
    url: https://uat.prodexity.com/bsimmcalc
  script:
    - "echo 'deploying to uat...'"

deploy_to_prod:
  stage: deploy
  environment:
    name: production
    url: https://bsimmcalc.prodexity.com
  script:
    - "echo 'deploying to prod...'"
  when: manual
  only:
    - master
