image: "ruby:2.3"

stages:
  - test
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq ruby-dev nodejs libsqlite3-dev graphviz
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor/bundle

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/bundle

test:
  stage: test
  script:
    - bundle exec rails db:migrate
    - bundle exec rails db:seed
    - bundle exec rails test
  coverage: '/Coverage.*?\d+\s*\/\s*\d+\s*LOC\s*\((.*?%)\)\s*covered\./'

rubocop:
  stage: test
  script:
    - bundle exec rubocop

brakeman:
  stage: test
  script:
    - bundle exec brakeman

deploy_to_uat:
  stage: deploy
  environment:
    name: uat
    url: https://uat.bsimmcalc.prodexity.com
  script:
    - mkdir -p ~/.ssh
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo $BSIMMCALC_UAT_SSH_KEY | sed 's/ RSA PRIVATE KEY/RSAPRIVKEY/g' | sed 's/ /\n/g' | sed 's/RSAPRIVKEY/ RSA PRIVATE KEY/g' > ~/.ssh/id_rsa
    - bundle exec cap uat deploy
    - bundle exec cap uat deploy:seed
    - rm ~/.ssh/id_rsa

deploy_to_prod:
  stage: deploy
  environment:
    name: production
    url: https://bsimmcalc.prodexity.com
  script:
    - mkdir -p ~/.ssh
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo $BSIMMCALC_PROD_SSH_KEY | sed 's/ RSA PRIVATE KEY/RSAPRIVKEY/g' | sed 's/ /\n/g' | sed 's/RSAPRIVKEY/ RSA PRIVATE KEY/g' > ~/.ssh/id_rsa
    - bundle exec cap production deploy
    - bundle exec cap production deploy:seed
    - rm ~/.ssh/id_rsa
  when: manual
  only:
    - master
